Repository mgm-interns/teamradio2-frontend, pull requests merged in 2018-05, with the labels that each got.

#229 Show notification image size
  src/Modules/User/Components/Profile/ImageUploader/ImageUploader.tsx
  src/Modules/User/Constants/Constants.ts
Labels: front-end

#228 Implement service worker with webpack in production build
  config/paths.js
  config/webpack.config.prod.js
  package.json
  src/Configuration/ServiceWorker/index.ts
  src/Configuration/ServiceWorker/register.ts
  src/Helpers/BrowserHelper/BrowserHelper.ts
  src/index.tsx
Labels: enhancement, front-end

#212 Append access token to headers for SSE traffic
  package.json
  src/Services/Header/Header.ts
  src/Services/Header/index.ts
  src/Services/Http/HttpServices/HttpServices.ts
  src/Services/SSE/SSEService/EventSourcePolyfill.ts
  src/Services/SSE/SSEService/SSEService.ts
Labels: enhancement, front-end, pending

#242 Fix images and fonts asset prefix in resources
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  scss/_custom.scss
  src/Pages/ForgotPassword/ForgotPassword.scss
  src/Pages/Help/Help.scss
  src/Pages/Home/Main/Main.scss
  src/Pages/Login/Login.scss
  src/Pages/Register/Register.scss
  src/Pages/ResetPassword/ResetPassword.scss
Labels: front-end

#241 Implement lazyload for homepage
  package.json
  src/Pages/Home/Sections/AddingSongSection.tsx
  src/Pages/Home/Sections/CreatingSection.tsx
  src/Pages/Home/Sections/SharingSection.tsx
Labels: enhancement, front-end

#251 Change default avatar for all project
  public/img/avatars/1.jpg
  public/img/avatars/2.jpg
  public/img/avatars/3.jpg
  public/img/avatars/4.jpg
  public/img/avatars/5.jpg
  public/img/avatars/6.jpg
  public/img/avatars/7.jpg
  public/img/avatars/8.jpg
  public/img/avatars/default.svg
  src/Modules/Station/Components/PlaylistTabs/fixture.ts
  src/Modules/User/Constants/Constants.ts
Labels: front-end

#245 Create Base component for song item
  src/Components/Components.tsx
  src/Components/SongItem/SongItem.tsx
  src/Components/SongItem/index.tsx
  src/Models/Song/PlaylistSong.ts
  src/Modules/Station/Components/PlaylistTabs/Favorite/FavoriteItem/FavoriteItem.tsx
  src/Modules/Station/Components/PlaylistTabs/History/HistoryItem/HistoryItem.tsx
  src/Modules/Station/Components/PlaylistTabs/Playlist/PlaylistItem/PlaylistItem.tsx
Labels: front-end

#232 Implement Online Users - UI
  src/Modules/Station/Components/Components.tsx
  src/Modules/Station/Components/OnlineUsers/OnlineUsers.scss
  src/Modules/Station/Components/OnlineUsers/OnlineUsers.tsx
  src/Modules/Station/Components/OnlineUsers/index.tsx
  src/Modules/Station/Components/StationHeader/StationHeader.scss
  src/Modules/Station/Components/StationHeader/StationHeader.tsx
Labels: front-end

#267 Implement dependencies injection
  package.json
  src/Configuration/DependencyInjection/DependencyInjection.ts
  src/Configuration/DependencyInjection/container.ts
  src/Configuration/DependencyInjection/index.ts
  src/Modules/Station/Components/AddSong/AddSong.tsx
  src/Modules/Station/Components/ChatBox/ChatBox.tsx
  src/Modules/Station/Components/ConfigurationButton/ConfigurationButton.tsx
  src/Modules/Station/Components/CreateStation/CreateStation.tsx
  src/Modules/Station/Components/PlaylistTabs/Favorite/Favorite.tsx
  src/Modules/Station/Components/PlaylistTabs/History/History.tsx
  src/Modules/Station/Components/PlaylistTabs/Playlist/Playlist.tsx
  src/Modules/Station/Components/PlaylistTabs/Playlist/PlaylistItem/PlaylistItem.tsx
  src/Modules/Station/Components/PlaylistTabs/PlaylistTabs.tsx
  src/Modules/Station/Components/StationBrowser/StationBrowser.tsx
  src/Modules/Station/Components/StationHeader/StationHeader.tsx
  src/Modules/User/Components/Login/ButtonFacebookLogin/FacebookLogin.tsx
  src/Modules/User/Components/Login/ButtonGoogleLogin/ButtonGoogleLogin.tsx
  src/Modules/User/Components/Login/LoginForm/LoginForm.tsx
  src/Modules/User/Components/Login/LoginWrapper.tsx
  src/Modules/User/Components/Password/ForgotPassword/ForgotPasswordForm.tsx
  src/Modules/User/Components/Password/PasswordForm/PasswordForm.tsx
  src/Modules/User/Components/Password/ResetPassword/ResetPasswordForm.tsx
  src/Modules/User/Components/Profile/Favorite/Favorite.tsx
  src/Modules/User/Components/Profile/Favorite/FavoriteItem/FavoriteItem.tsx
  src/Modules/User/Components/Profile/ImageUploader/ImageUploader.tsx
  src/Modules/User/Components/Profile/InformationForm/InformationForm.tsx
  src/Modules/User/Components/Profile/MyStationsBrowser/MyStationsBrowser.tsx
  src/Modules/User/Components/Profile/ProfileHeader/ProfileHeader.tsx
  src/Modules/User/Components/Profile/RecentStationsBrowser/RecentStationsBrowser.tsx
  src/Modules/User/Components/Profile/UserDropdown/UserDropdown.tsx
  src/Modules/User/Components/Register/RegisterForm/RegisterForm.tsx
  src/Services/Http/StationServices/SongServices.ts
  src/Services/Http/StationServices/StationServices.ts
  src/Services/Http/UserServices/UserServices.ts
  src/Services/SSE/SSE.ts
  src/Services/SSE/StationChatSSE.ts
  src/Services/SSE/StationChatSSEService.ts
  src/Services/SSE/StationPlaylistSSE.ts
  src/Services/SSE/StationPlaylistSSEService.ts
  src/Services/SSE/index.ts
  src/index.tsx
  tsconfig.json
Labels: enhancement, front-end

#233 Fix station browser items to sync it with new change from Backend
  src/BaseComponent/BaseComponent.tsx
  src/BaseComponent/BaseStationBrowser/BaseStationBrowser.tsx
  src/BaseComponent/BaseStationBrowser/index.ts
  src/Components/StationBrowserSlider/StationBrowserSlider.tsx
  src/Configuration/Redux/Reducers.ts
  src/Models/Models.ts
  src/Models/Station/StationItemsControlledMap.ts
  src/Models/Station/StationItemsMap.ts
  src/Models/Station/index.ts
  src/Modules/Station/Components/StationBrowser/StationBrowser.scss
  src/Modules/Station/Components/StationBrowser/StationBrowser.tsx
  src/Modules/Stations/Redux/Constants.ts
  src/Modules/Stations/Redux/Reducers.ts
  src/Modules/Stations/Redux/Types.ts
  src/Modules/Stations/Redux/index.ts
  src/Modules/Stations/index.ts
  src/Modules/User/Components/Profile/MyStationsBrowser/MyStationsBrowser.tsx
  src/Modules/User/Components/Profile/MyStationsBrowser/UserStationsBrowser.tsx
  src/Modules/User/Components/Profile/RecentStationsBrowser/MyRecentStationsBrowser.tsx
  src/Modules/User/Components/Profile/RecentStationsBrowser/UserRecentStationsBrowser.tsx
  src/Pages/Station/Station.tsx
  src/Services/Http/StationServices/StationServices.ts
  src/Services/SSE/SSEService/SSEService.ts
  src/Services/SSE/StationsBrowserSSE.ts
  src/Services/SSE/index.ts
Labels: front-end

#298 Direct to user's profile when click on avatar in Playlist and History
  src/Components/SongItem/SongItem.tsx
Labels: front-end

#295 Implement paging for stations browser
  src/Components/StationBrowserSlider/StationBrowserSlider.tsx
  src/Modules/Station/Components/StationBrowser/BaseStationBrowser.tsx
  src/Modules/Station/Components/StationBrowser/StationBrowser.tsx
  src/Modules/Stations/Redux/Reducers.ts
  src/Services/SSE/StationsBrowserSSE.ts
Labels: front-end

#302 Fix station tabs's height
  src/Modules/Station/Components/PlaylistTabs/PlaylistTabs.scss
  src/Pages/Station/Station.scss
Labels: bug

#303 Add update history when user switch station
  src/Modules/Station/Components/PlaylistTabs/History/History.tsx
  src/Modules/Station/Components/PlaylistTabs/PlaylistTabs.tsx
Labels: front-end

#306 Change 'Bad credentials' to 'Invalid username or password'
  src/Modules/User/Components/Login/LoginForm/LoginForm.tsx
Labels: front-end

#307 Make no player mode more attractive
  src/Modules/Station/Components/NowPlaying/NowPlaying.scss
  src/Modules/Station/Components/NowPlaying/NowPlaying.tsx
  src/Pages/Station/Station.tsx
Labels: front-end, question

#336 Implemented anonymous station
  src/Services/Http/HttpServices/HttpServices.ts
Labels: front-end

#355 Show a "Not Found" icon when the search result is not found (Search b…
  src/Modules/Station/Components/AddSong/SearchSong/SearchSong.tsx
Labels: different-to-old-version

#364 Remove redundant static asset import (improve web performance)
  package.json
  src/index.tsx
Labels: front-end

#384 Handle volume of the player and preview video
  src/Components/StationPlayer/StationPlayer.tsx
  src/Configuration/Redux/Reducers.ts
  src/Helpers/LocalStorageManager/LocalStorageManager.ts
  src/Models/Models.ts
  src/Models/Volume/Volume.ts
  src/Models/Volume/index.ts
  src/Modules/Station/Components/AddSong/AddSong.tsx
  src/Modules/Station/Components/AddSong/PreviewVideo/PreviewVideo.tsx
  src/Modules/Station/Components/NowPlaying/NowPlaying.tsx
  src/Modules/Station/Components/StationHeader/StationHeader.tsx
  src/Modules/Station/Redux/Actions/Actions.ts
  src/Modules/Station/Redux/Constants/Constants.ts
  src/Modules/Station/Redux/Constants/Volume.ts
  src/Modules/Station/Redux/Reducer/Reducer.ts
  src/Modules/Station/Redux/Reducer/Volume.ts
  src/Modules/Station/Redux/Types/IVolume.ts
  src/Modules/Station/Redux/Types/Types.ts
  src/Pages/Station/Station.tsx
Labels: bug, different-to-old-version, front-end

#383 Do not show invalid access token in client
  src/Modules/User/Components/Profile/UserDropdown/UserDropdown.tsx
Labels: front-end

#387 Cancel subscribe to prevent Error message everywhere
  src/Modules/Station/Components/PlaylistTabs/History/History.tsx
  src/Modules/User/Components/Profile/Favorite/Favorite.tsx
  src/Modules/User/Components/Profile/MyStationsBrowser/MyStationsBrowser.tsx
  src/Modules/User/Components/Profile/MyStationsBrowser/UserStationsBrowser.tsx
  src/Modules/User/Components/Profile/RecentStationsBrowser/MyRecentStationsBrowser.tsx
  src/Modules/User/Components/Profile/RecentStationsBrowser/UserRecentStationsBrowser.tsx
Labels: front-end

#394 Ignore the unnecessary error messages
  src/Modules/Station/Components/ChatBox/ChatBox.tsx
  src/Modules/Station/Components/PlaylistTabs/Favorite/Favorite.tsx
  src/Modules/Station/Components/PlaylistTabs/History/History.tsx
  src/Modules/Station/Components/PlaylistTabs/PlaylistTabs.tsx
  src/Modules/User/Components/Login/LoginWrapper.tsx
  src/Modules/User/Components/Profile/Favorite/Favorite.tsx
  src/Modules/User/Components/Profile/InformationForm/InformationForm.tsx
  src/Modules/User/Components/Profile/MyStationsBrowser/MyStationsBrowser.tsx
  src/Modules/User/Components/Profile/MyStationsBrowser/UserStationsBrowser.tsx
  src/Modules/User/Components/Profile/ProfileHeader/ProfileHeader.tsx
  src/Modules/User/Components/Profile/RecentStationsBrowser/MyRecentStationsBrowser.tsx
  src/Modules/User/Components/Profile/RecentStationsBrowser/UserRecentStationsBrowser.tsx
  src/Modules/User/Components/Profile/UserDropdown/UserDropdown.tsx
  src/Pages/Profile/ProfileNavBar/PublicProfileNavBar.tsx
Labels: front-end

#404 Fix playlist has two scroll bar
  src/Modules/Station/Components/PlaylistTabs/Playlist/Playlist.scss
Labels: bug

#412 Abandon private station feature
  src/Modules/Station/Components/CreateStation/CreateStation.tsx
Labels: front-end

#411 Clear history list before switch station
  src/Modules/Station/Components/PlaylistTabs/History/History.tsx
Labels: front-end
