Repository mgm-interns/teamradio2-frontend, pull requests merged in 2018-03, with the labels that each got.

#51 Apply absolute import and purge unused dependencies
  .babelrc
  .editorconfig
  package.json
  src/Components/Breadcrumb/Breadcrumb.tsx
  src/Components/Header/Header.tsx
  src/Components/ImageUploader/ImageUploader.tsx
  src/Components/Sidebar/Sidebar.tsx
  src/Containers/FullLayout/FullLayout.tsx
  src/Containers/NoSideBarLayout/NoSideBarLayout.tsx
  src/Modules/User/Components/ForgotPassword/ForgotPasswordForm.tsx
  src/Modules/User/Components/InformationForm/InformationForm.tsx
  src/Modules/User/Components/Login/LoginForm.tsx
  src/Modules/User/Components/PasswordForm/PasswordForm.tsx
  src/Modules/User/Components/Register/RegisterForm.tsx
  src/Modules/User/Components/ResetPassword/ResetPasswordForm.tsx
  src/Pages/ForgotPassword/ForgotPassword.tsx
  src/Pages/Home/Main/Main.tsx
  src/Pages/Login/Login.tsx
  src/Pages/Profile/ProfileHeader/ProfileHeader.tsx
  src/Pages/Profile/ProfileNavBar/SelectFormButton/SelectFormButton.tsx
  src/Pages/Register/ExtraInformationForm.tsx
  src/Pages/Register/Register.tsx
  src/Pages/ResetPassword/ResetPassword.tsx
  tsconfig.json
  webpack.config.js
Labels: enhancement, front-end

#64 Fix styles in the Login, Forgot password and Register forms
  src/Components/Footer/Footer.scss
  src/Containers/NoSideBarLayout/NoSideBarLayout.scss
  src/Pages/ForgotPassword/ForgotPassword.scss
  src/Pages/ForgotPassword/ForgotPassword.tsx
  src/Pages/Login/Login.scss
  src/Pages/Login/Login.tsx
Labels: bug

#55 Favourite history layout
  scss/_custom.scss
  src/Modules/Station/Components/Components.tsx
  src/Modules/Station/Components/Favourite/Favourite.tsx
  src/Modules/Station/Components/Favourite/FavouriteItem/FavouriteItem.tsx
  src/Modules/Station/Components/Favourite/FavouriteItem/index.tsx
  src/Modules/Station/Components/Favourite/index.tsx
  src/Modules/Station/Components/History/History.tsx
  src/Modules/Station/Components/History/HistoryItem/HistoryItem.tsx
  src/Modules/Station/Components/History/HistoryItem/index.tsx
  src/Modules/Station/Components/History/index.tsx
Labels: front-end
