Repository mgm-interns/teamradio2-frontend, pull requests merged in 2018-04, with the labels that each got.

#73 Fix header style
  src/Components/CustomHeader/CustomHeader.scss
  src/Components/CustomHeader/CustomHeader.tsx
Labels: bug

#84 Implement RadioSSE handler
  src/Services/SSE/IRadioSSE.ts
  src/Services/SSE/RadioSSE.ts
  src/Services/SSE/index.ts
Labels: front-end

#96 craete models for user, song and favorite
  src/Models/FavoriteSong/FavoriteSong.ts
  src/Models/FavoriteSong/index.ts
  src/Models/Models.ts
  src/Models/Song/Song.ts
  src/Models/Song/index.ts
  src/Models/User/User.ts
Labels: front-end

#99 Remove scrolling from forgot password layout
  src/Pages/ForgotPassword/ForgotPassword.scss
  src/Pages/ForgotPassword/ForgotPassword.tsx
Labels: bug

#107 remove station list when have no data in home page
  src/Modules/Station/Components/StationBrowser/StationBrowser.tsx
Labels: front-end

#113 Apply SSE data to player and seek player time from Redux store
  src/Components/StationPlayer/StationPlayer.tsx
  src/Helpers/DateTimeHelper/DateTimeHelper.ts
  src/Helpers/DateTimeHelper/index.ts
  src/Helpers/YoutubeHelper/YoutubeHelper.ts
  src/Models/Song/NowPlayingSong.ts
  src/Models/Song/index.ts
  src/Modules/Station/Components/NowPlaying/NowPlaying.tsx
  src/Modules/Station/Components/PlaylistTabs/Playlist/Playlist.tsx
  src/Modules/Station/Components/PlaylistTabs/Playlist/PlaylistItem/PlaylistItem.tsx
  src/Modules/Station/Redux/Types/Types.ts
Labels: front-end

#135 Fix station browser item style
  src/Modules/Station/Components/StationBrowser/StationBrowser.scss
  src/Modules/Station/Components/StationBrowser/StationBrowserItem/StationBrowserItem.scss
  src/Modules/Station/Components/StationBrowser/StationBrowserItem/StationBrowserItem.tsx
Labels: bug, front-end, urgent

#136 Implement router event in station page
  src/Modules/Station/Components/PlaylistTabs/PlaylistTabs.tsx
  src/Modules/Station/Components/StationHeader/StationHeader.tsx
  src/Pages/Station/Station.tsx
Labels: front-end

#118 Implement passive mode
  src/Modules/Station/Components/StationHeader/StationHeader.scss
  src/Modules/Station/Components/StationHeader/StationHeader.tsx
  src/Pages/Station/Station.scss
  src/Pages/Station/Station.tsx
Labels: front-end

#148 Implement Facebook login
  .env
  env/.env.dev
  src/Modules/User/Components/Login/FacebookLogin/FacebookLogin.tsx
  src/Modules/User/Components/Login/FacebookLogin/FacebookLoginWithButton.tsx
  src/Modules/User/Components/Login/FacebookLogin/index.ts
  src/Modules/User/Components/Login/LoginByThirdParty.tsx
Labels: front-end

#149 Create favorite in playlisttabs of station page
  src/Modules/Station/Components/PlaylistTabs/Favourite/FavouriteItem/FavouriteItem.tsx
  src/Modules/Station/Components/PlaylistTabs/Playlist/Playlist.tsx
  src/Modules/Station/Components/PlaylistTabs/Playlist/PlaylistItem/PlaylistItem.tsx
  src/Modules/Station/Components/PlaylistTabs/PlaylistTabs.tsx
  src/Services/Http/UserServices/UserServices.ts
Labels: front-end

#147 Update user info in Profile and Header
  src/Components/Components.tsx
  src/Components/CustomHeader/CustomHeader.tsx
  src/Components/UserInfo/UserInfo.tsx
  src/Components/UserInfo/index.tsx
  src/Configuration/Redux/Reducers.ts
  src/Helpers/LocalStorageManager/LocalStorageManager.ts
  src/Modules/User/Components/Components.tsx
  src/Modules/User/Components/Profile/ImageUploader/ImageUploader.scss
  src/Modules/User/Components/Profile/ImageUploader/ImageUploader.tsx
  src/Modules/User/Components/Profile/ImageUploader/index.tsx
  src/Modules/User/Components/Profile/InformationForm/FormWrapper.tsx
  src/Modules/User/Components/Profile/InformationForm/InformationForm.scss
  src/Modules/User/Components/Profile/InformationForm/InformationForm.tsx
  src/Modules/User/Components/Profile/InformationForm/index.tsx
  src/Modules/User/Components/Profile/Profile.tsx
  src/Modules/User/Components/Profile/ProfileHeader/ProfileHeader.tsx
  src/Modules/User/Components/Profile/UserDropdown/UserDropdown.scss
  src/Modules/User/Components/Profile/UserDropdown/UserDropdown.tsx
  src/Modules/User/Components/Profile/UserDropdown/index.tsx
  src/Modules/User/Components/Profile/index.tsx
  src/Modules/User/Redux/Actions/Actions.ts
  src/Modules/User/Redux/Actions/ProfileAction.ts
  src/Modules/User/Redux/Actions/sampleActions.ts
  src/Modules/User/Redux/Constants/Constants.ts
  src/Modules/User/Redux/Constants/ProfileConstants.ts
  src/Modules/User/Redux/Constants/sampleConstants.ts
  src/Modules/User/Redux/Reducer/ProfileReducer.ts
  src/Modules/User/Redux/Reducer/Reducer.ts
  src/Modules/User/Redux/Reducer/sampleReducer.ts
  src/Modules/User/Redux/Types/ProfileType.ts
  src/Modules/User/Redux/Types/Types.ts
  src/Modules/User/Redux/Types/sampleTypes.ts
  src/Pages/Profile/Profile.tsx
  src/Pages/Profile/ProfileNavBar/SelectFormButton/SelectFormButton.tsx
Labels: front-end

#146 Enhance station player seek time
  src/Components/StationPlayer/StationPlayer.scss
  src/Components/StationPlayer/StationPlayer.tsx
  src/Modules/Station/Components/NowPlaying/NowPlaying.tsx
  src/Pages/Station/Station.scss
Labels: enhancement, front-end, urgent

#117 Implement Notifications
  package.json
  src/BaseComponent/BaseComponent.tsx
  src/BaseComponent/NotificationInstance.ts
  src/BaseComponent/index.tsx
  src/Containers/NoSideBarLayout/NoSideBarLayout.tsx
  src/Models/Notification/Notification.ts
  src/Models/Notification/index.ts
  src/Modules/Station/Components/CreateStation/CreateStation.tsx
Labels: front-end

#162 Get favorite list in profile
  src/Modules/User/Components/Profile/Favorite/Favorite.scss
  src/Modules/User/Components/Profile/Favorite/Favorite.tsx
  src/Modules/User/Components/Profile/Favorite/FavoriteItem/FavoriteItem.scss
  src/Modules/User/Components/Profile/Favorite/FavoriteItem/FavoriteItem.tsx
  src/Modules/User/Components/Profile/Favorite/FavoriteItem/index.tsx
  src/Modules/User/Components/Profile/Favorite/index.tsx
  src/Modules/User/Components/Profile/Profile.tsx
  src/Pages/Profile/ProfileNavBar/ProfileNavBar.scss
  src/Pages/Profile/ProfileNavBar/ProfileNavBar.tsx
Labels: front-end

#177 Fix header style and routing
  src/Components/CustomHeader/CustomHeader.scss
  src/Components/CustomHeader/CustomHeader.tsx
  src/Modules/User/Components/Profile/UserDropdown/UserDropdown.scss
  src/Modules/User/Components/Profile/UserDropdown/UserDropdown.tsx
Labels: front-end

#172 Implement friendly id for station
  src/Models/Models.ts
  src/Models/Station/Station.ts
  src/Models/Station/StationItem.ts
  src/Models/Station/index.ts
  src/Modules/Station/Components/StationBrowser/StationBrowser.tsx
  src/Modules/Station/Components/StationBrowser/StationBrowserItem/StationBrowserItem.tsx
Labels: front-end

#184 Fix typing for react-redux in authorization components
  src/Modules/Station/Components/AddSong/AddSong.tsx
  src/Modules/User/Components/Profile/ImageUploader/ImageUploader.tsx
  src/Modules/User/Components/Profile/InformationForm/InformationForm.tsx
Labels: front-end

#199 Rework StationBrowserSlider with less code and less bugs
  src/Components/StationBrowserSlider/StationBrowserSlider.scss
  src/Components/StationBrowserSlider/StationBrowserSlider.tsx
  src/Modules/Station/Components/StationBrowser/StationBrowser.scss
  src/Modules/Station/Components/StationBrowser/StationBrowser.tsx
Labels: enhancement, front-end

#197 Add delete favorite function in profile and refactor favorite tabs
  src/Models/FavoriteSong/FavoriteSong.ts
  src/Models/FavoriteSong/FavoriteSongItem.ts
  src/Modules/Station/Components/PlaylistTabs/Favorite/Favorite.tsx
  src/Modules/Station/Components/PlaylistTabs/Favorite/FavoriteItem/FavoriteItem.tsx
  src/Modules/Station/Components/PlaylistTabs/Playlist/Playlist.tsx
  src/Modules/Station/Components/PlaylistTabs/Playlist/PlaylistItem/PlaylistItem.tsx
  src/Modules/Station/Components/PlaylistTabs/PlaylistTabs.tsx
  src/Modules/User/Components/Profile/Favorite/Favorite.tsx
  src/Modules/User/Components/Profile/Favorite/FavoriteItem/FavoriteItem.scss
  src/Modules/User/Components/Profile/Favorite/FavoriteItem/FavoriteItem.tsx
  src/Modules/User/Redux/Actions/Actions.ts
  src/Modules/User/Redux/Types/Types.ts
  src/Pages/Profile/ProfileNavBar/ProfileNavBar.scss
Labels: front-end

#205 Implement Add song to playlist from favourite list
  src/Modules/Station/Components/PlaylistTabs/Favorite/Favorite.tsx
  src/Modules/Station/Components/PlaylistTabs/Favorite/FavoriteItem/FavoriteItem.tsx
  src/Modules/Station/Components/PlaylistTabs/History/HistoryItem/HistoryItem.tsx
  src/Modules/Station/Components/PlaylistTabs/PlaylistTabs.tsx
Labels: front-end

#191 Implement Skip rule Configuration in frontend
  src/Models/Models.ts
  src/Models/Station/Configuration.ts
  src/Models/Station/Station.ts
  src/Models/Station/index.ts
  src/Modules/Station/Components/Components.tsx
  src/Modules/Station/Components/ConfigurationButton/ConfigurationButton.tsx
  src/Modules/Station/Components/StationHeader/StationHeader.tsx
  src/Services/Http/StationServices/StationServices.ts
Labels: front-end

#216 Webpack 4, React 16.3.2 and production script
  .babelrc
  .babelrc.js
  .gitignore
  config/paths.js
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  package.json
  scss/core/_layout.scss
  scss/core/_variables.scss
  src/index.tsx
  tslint.json
  webpack.config.js
  yarn.lock
Labels: enhancement, front-end

#221 Implement ForgotPassword
  src/Models/Models.ts
  src/Models/User/EmailForm.ts
  src/Models/User/index.ts
  src/Modules/User/Components/Password/ForgotPassword/ForgotPasswordForm.tsx
  src/Modules/User/Components/Password/ForgotPassword/InnerForm.tsx
  src/Pages/ForgotPassword/ForgotPassword.tsx
  src/Services/Http/UserServices/UserServices.ts
Labels: front-end

#224 Implement Reset password
  src/Containers/NoSideBarLayout/NoSideBarLayout.tsx
  src/Modules/User/Components/Password/ResetPassword/InnerForm.tsx
  src/Modules/User/Components/Password/ResetPassword/ResetPasswordForm.tsx
  src/Pages/ResetPassword/ResetPassword.tsx
  src/Services/Http/UserServices/UserServices.ts
Labels: front-end

#226 Improve UI while rendering empty list in station Page & Fix Add song text
  src/Components/StationPlayer/StationPlayer.scss
  src/Components/StationPlayer/StationPlayer.tsx
  src/Modules/Station/Components/AddSong/SearchSong/SearchSong.tsx
  src/Modules/Station/Components/PlaylistTabs/Favorite/Favorite.tsx
  src/Modules/Station/Components/PlaylistTabs/History/History.tsx
  src/Modules/Station/Components/PlaylistTabs/Playlist/Playlist.scss
  src/Modules/Station/Components/PlaylistTabs/Playlist/Playlist.tsx
  src/Modules/Station/Components/PlaylistTabs/PlaylistTabs.scss
Labels: front-end
